[package]
name = "tokenizer_cereal"
version = "0.1.0"
authors = ["Enrico \"erolm_a\" Trombetta <trombetta.enricom@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tokenizer_cereal"
crate-type = ["cdylib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies.pyo3]
version="0.12.4"

[dependencies]
tokenizers = "*"
serde = { version = "1.0", features = ["derive"]}
bincode = "*"
anyhow = "*"
simple-error = "*"
itertools="0.9.0"
paste="1.0"
indicatif="*"
crossbeam="*"
log="0.4.13"
memmap="0.7.0"


[profile.dev]
# enable moderate optimizations while keeping debug mode on
opt-level = 1