[package]
name = "tokenizer_cereal"
version = "0.1.0"
authors = ["Enrico \"erolm_a\" Trombetta <trombetta.enricom@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tokenizer_cereal"
crate-type = ["cdylib"]
features = ["extension-module"]

[dependencies.pyo3]
version="0.12.4"
features = ["extension-module"]

[dependencies]
tokenizers = "*"
serde = { version = "1.0", features = ["derive"]}
serde_cbor = "0.11.1"
bincode = "*"
anyhow = "*"
simple-error = "*"
itertools="0.9.0"
paste="1.0"